Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.ssh.insert_key = false

  # config.vm.synced_folder "../scripts/dns", "/vagrant/dns", type: "rsync"

  config.vm.network "forwarded_port",
    guest: 80, host: 80

  config.vm.network "forwarded_port",
    guest: 123, host: 123

  config.vm.network "forwarded_port",
    guest: 389, host: 389

    config.vm.network "forwarded_port",
      guest: 443, host: 443

  config.vm.network "forwarded_port",
    guest: 8500, host: 8500

  config.vm.network "forwarded_port",
    guest: 8600, host: 8600, protocol: "udp"

  config.vm.provision "shell",
    inline: "sudo yum install -y ansible"

  config.vm.provision "file",
    source: "../ansible/docker-host-playbook.yml", destination: "/vagrant/docker-host-playbook.yml"

  config.vm.provision "file",
    source: "../docker/docker-compose.yml",destination: "/vagrant/docker-compose.yml"

  config.vm.provision "file",
    source: "../scripts/dns.sh",destination: "/vagrant/dns.sh"

  config.vm.provision "file",
    source: "../scripts/dns/ldap.json",destination: "/vagrant/ldap.json"

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "./docker-host-playbook.yml"
  end

  # config.vm.provision "shell",
  #   inline: "/usr/local/bin/docker-compose -f /vagrant/docker-compose.yml up -d"

  # config.vm.provision "shell",
  #   inline: "chmod a+x /vagrant/dns.sh"
  #
  # config.vm.provision "shell",
  #   inline: "/vagrant/dns.sh"

end
