Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.ssh.insert_key = false

  # config.vm.synced_folder "../scripts/dns", "/vagrant/dns", type: "rsync"

  # config.vm.network "forwarded_port",
  #   guest: 80, host: 80

  # config.vm.network "forwarded_port",
  #   guest: 123, host: 123
  #
  config.vm.network "forwarded_port",
    guest: 10389, host: 10389

  # config.vm.network "forwarded_port",
  #   guest: 443, host: 443

  config.vm.network "forwarded_port",
    guest: 8500, host: 8500

  config.vm.network "forwarded_port",
    guest: 8600, host: 8600, protocol: "udp"

  # config.vm.network "forwarded_port",
  #   guest: 8080, host: 8080

  config.vm.provision "shell",
    inline: "sudo yum install -y ansible"

  config.vm.provision "file",
    source: "../consul", destination: "/tmp/"


  config.vm.provision "file",
    source: "../ansible/non-docker-playbook.yml", destination: "/vagrant/non-docker-playbook.yml"

  # config.vm.provision "file",
  #   source: "../docker/docker-compose.yml",destination: "/vagrant/docker-compose.yml"

  # config.vm.provision "file",
  #   source: "../scripts",destination: "/vagrant/scripts"
  #
  # config.vm.provision "shell",
  #   inline: "chmod a+x /vagrant/scripts/dns.sh"

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "./non-docker-playbook.yml"
  end

  # TODO - need to move this out of vagrant and into docker-compose
  # config.vm.provision "shell",
  #   inline: "/vagrant/scripts/dns.sh"

end
