Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.ssh.insert_key = false

  config.vm.network "public_network"

  config.vm.provision "shell",
    inline: "sudo yum install -y ansible"

  config.vm.provision "file",
    source: "../ansible/docker-host-playbook.yml", destination: "/vagrant/docker-host-playbook.yml"
  config.vm.provision "file",
    source: "../docker/docker-compose.yml",destination: "/vagrant/docker-compose.yml"

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "./docker-host-playbook.yml"
  end

  config.vm.provision "shell",
    inline: "docker-compose -d -f /vagrant/docker-compose.yml"
end
