version: '3'
services:
  # db:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=welcome
  # nifi:
  #   image: apache/nifi:1.4.0
  #   ports:
  #     - 8181:8181
  #     - 8080:8080
  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  consul:
    image: consul
    ports:
      - 8600:8600/udp
      - 8500:8500
  # ntp:
  #   image: cloudwattfr/ntpserver
  #   ports:
  #     - 123:123
  # ldap:
  #   image: osixia/openldap:1.1.8
  #   ports:
  #     - 389:389
  # ldapadmin:
  #   image: osixia/phpldapadmin:0.7.0
  #   ports:
