version: '3'
services:
  # db:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=welcome
  # nifi:
  #   image: apache/nifi:1.4.0
  #   ports:
  #     - 8181:8181
  #     - 8080:8080
  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  consul:
    image: consul
    ports:
      - 8600:8600/udp
      - 8500:8500
    # exec:
    #   - docker exec consul curl -XPUT http://localhost:8500/v1/agent/service/register -d @ldap.json
      # - docker exec consul curl -XPUT http://localhost:8500/v1/agent/service/register -d "{\"ID\": \"ldap1\",\"Name\"\: \"ldap\",\"Address\"\: \"127.0.0.1\",\"Port\"\: 389}"
      # - docker exec consul curl -XPUT http://localhost:8500/v1/agent/service/register -d "{\"ID\": \"ntp1\",\"Name\": \"ntp\",\"Address\": \"127.0.0.1\",\"Port\": 123}"
  ntp:
    image: cloudwattfr/ntpserver
    ports:
      - 8123:123
  ldap:
    image: openmicroscopy/apacheds
    ports:
      - 389:10389
